name: academy_erp
description: 학원 맞춤 ERP 시스템 (학생 앱 + 관리자 웹)

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  provider: ^6.1.2
  supabase_flutter: ^2.12.2
  intl: ^0.20.2

  # 🔥 여기만 수정
  file_picker: ^6.1.1
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/